#!/usr/bin/env python
import pygooglechart
import sqlite3
def query_db_chartable(db_name, host, service):
	conn = sqlite3.connect(db_name +".db")
	cursor = conn.cursor()
	sql_statement = """select value, time from data where host like ? and service like ? order by time limit 65"""
	cursor.execute(sql_statement, (host, service) )
	result = cursor.fetchall()
	cursor.close()
	return result


if __name__ =="__main__":
	database_name = "it"
	results = query_db_chartable(database_name, "iinet", "HTTP")
	counts = [float(x[0]) for x in results]
	time_lable = [str(x[1]) for x in results]
	chart = pygooglechart.SimpleLineChart(700,400)
	chart.add_data(counts)
	chart.set_axis_range(pygooglechart.Axis.LEFT, 0, max(counts))
	first = time_lable[0]
	last = time_lable[int(len(time_lable) -1)]
	index = chart.set_axis_labels(pygooglechart.Axis.BOTTOM, [first, last])
	chart.set_axis_style(index, "202020", font_size=9, alignment=-1)
	print chart.get_url()

